package com.steelstorm.arsenal.client;

import net.minecraft.client.model.HumanoidModel;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Cube layout of the 3D celestial armour. Generated by tools/gen_armor3d.py together with its
 * textures; edit the script, not this file.
 */
public final class CelestialArmorLayers {
    public static LayerDefinition outer() {
        MeshDefinition mesh = HumanoidModel.createMesh(CubeDeformation.NONE, 0.0F);
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("head", CubeListBuilder.create()
                .texOffs(0, 0).mirror(false).addBox(-4F, -8F, -4F, 8F, 8F, 8F, new CubeDeformation(1.0F))
                .texOffs(94, 36).mirror(false).addBox(-4.5F, -5.5F, -5.6F, 9F, 4F, 1F, new CubeDeformation(0.0F))
                .texOffs(74, 49).mirror(false).addBox(-3F, -4.5F, -5.9F, 6F, 1F, 1F, new CubeDeformation(0.0F))
                .texOffs(88, 0).mirror(false).addBox(-0.5F, -11F, -4.6F, 1F, 4F, 9F, new CubeDeformation(0.0F))
                .texOffs(56, 16).mirror(false).addBox(-6.5F, -9.5F, -2F, 1F, 5F, 5F, new CubeDeformation(0.0F))
                .texOffs(68, 16).mirror().addBox(5.5F, -9.5F, -2F, 1F, 5F, 5F, new CubeDeformation(0.0F))
                .texOffs(88, 49).mirror(false).addBox(-3.5F, -13F, -3.5F, 7F, 0.8F, 0.8F, new CubeDeformation(0.0F))
                .texOffs(104, 49).mirror(false).addBox(-3.5F, -13F, 2.7F, 7F, 0.8F, 0.8F, new CubeDeformation(0.0F))
                .texOffs(30, 36).mirror(false).addBox(-3.5F, -13F, -2.7F, 0.8F, 0.8F, 5.4F, new CubeDeformation(0.0F))
                .texOffs(44, 36).mirror().addBox(2.7F, -13F, -2.7F, 0.8F, 0.8F, 5.4F, new CubeDeformation(0.0F)),
                PartPose.offset(0F, 0F, 0F));
        root.addOrReplaceChild("hat", CubeListBuilder.create(),
                PartPose.offset(0F, 0F, 0F));
        root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(32, 0).mirror(false).addBox(-4F, 0F, -2F, 8F, 12F, 4F, new CubeDeformation(1.01F))
                .texOffs(104, 27).mirror(false).addBox(-4.2F, 0.5F, -3.8F, 8.4F, 7F, 1F, new CubeDeformation(0.0F))
                .texOffs(64, 44).mirror(false).addBox(-1.5F, 2.5F, -4.6F, 3F, 3F, 1F, new CubeDeformation(0.0F))
                .texOffs(0, 36).mirror(false).addBox(-4.5F, -1.5F, -3F, 9F, 2F, 6F, new CubeDeformation(0.0F))
                .texOffs(80, 16).mirror(false).addBox(-3.5F, 0.5F, 2.8F, 7F, 9F, 1F, new CubeDeformation(0.0F))
                .texOffs(72, 44).mirror(false).addBox(-11F, -3F, 3.4F, 7F, 3F, 1F, new CubeDeformation(0.0F))
                .texOffs(88, 44).mirror(false).addBox(-12F, 0F, 3.6F, 8F, 3F, 1F, new CubeDeformation(0.0F))
                .texOffs(106, 44).mirror(false).addBox(-11F, 3F, 3.8F, 7F, 3F, 1F, new CubeDeformation(0.0F))
                .texOffs(0, 49).mirror(false).addBox(-9F, 6F, 4.0F, 5F, 3F, 1F, new CubeDeformation(0.0F))
                .texOffs(12, 49).mirror().addBox(4F, -3F, 3.4F, 7F, 3F, 1F, new CubeDeformation(0.0F))
                .texOffs(28, 49).mirror().addBox(4F, 0F, 3.6F, 8F, 3F, 1F, new CubeDeformation(0.0F))
                .texOffs(46, 49).mirror().addBox(4F, 3F, 3.8F, 7F, 3F, 1F, new CubeDeformation(0.0F))
                .texOffs(62, 49).mirror().addBox(4F, 6F, 4.0F, 5F, 3F, 1F, new CubeDeformation(0.0F))
                .texOffs(0, 44).mirror(false).addBox(-4F, -2F, 3.2F, 8F, 3F, 1.2F, new CubeDeformation(0.0F)),
                PartPose.offset(0F, 0F, 0F));
        root.addOrReplaceChild("right_arm", CubeListBuilder.create()
                .texOffs(56, 0).mirror(false).addBox(-3F, -2F, -2F, 4F, 12F, 4F, new CubeDeformation(1.0F))
                .texOffs(0, 16).mirror(false).addBox(-5.5F, -4F, -3.5F, 7F, 4F, 7F, new CubeDeformation(0.0F))
                .texOffs(0, 27).mirror(false).addBox(-5.6F, -1.2F, -3.6F, 7.2F, 1F, 7.2F, new CubeDeformation(0.0F))
                .texOffs(20, 44).mirror(false).addBox(-5F, -7F, -1F, 1F, 3F, 2F, new CubeDeformation(0.0F))
                .texOffs(32, 27).mirror(false).addBox(-3.6F, 6F, -2.6F, 5F, 4F, 5F, new CubeDeformation(0.25F))
                .texOffs(0, 53).mirror(false).addBox(-3.6F, 7.5F, -2.9F, 5F, 1F, 1F, new CubeDeformation(0.0F)),
                PartPose.offset(-5F, 2F, 0F));
        root.addOrReplaceChild("left_arm", CubeListBuilder.create()
                .texOffs(72, 0).mirror().addBox(-1F, -2F, -2F, 4F, 12F, 4F, new CubeDeformation(1.0F))
                .texOffs(28, 16).mirror().addBox(-1.5F, -4F, -3.5F, 7F, 4F, 7F, new CubeDeformation(0.0F))
                .texOffs(52, 27).mirror().addBox(-1.6F, -1.2F, -3.6F, 7.2F, 1F, 7.2F, new CubeDeformation(0.0F))
                .texOffs(26, 44).mirror().addBox(4F, -7F, -1F, 1F, 3F, 2F, new CubeDeformation(0.0F))
                .texOffs(84, 27).mirror().addBox(-1.4F, 6F, -2.6F, 5F, 4F, 5F, new CubeDeformation(0.25F))
                .texOffs(12, 53).mirror().addBox(-1.4F, 7.5F, -2.9F, 5F, 1F, 1F, new CubeDeformation(0.0F)),
                PartPose.offset(5F, 2F, 0F));
        root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                .texOffs(96, 16).mirror(false).addBox(-2F, 6F, -2F, 4F, 6F, 4F, new CubeDeformation(1.0F))
                .texOffs(32, 44).mirror(false).addBox(-2.5F, 10F, -4.2F, 5F, 2F, 2.2F, new CubeDeformation(0.0F))
                .texOffs(58, 36).mirror(false).addBox(-2F, 4.5F, -3.7F, 4F, 5F, 1F, new CubeDeformation(0.0F))
                .texOffs(68, 36).mirror(false).addBox(-3.4F, 7F, -1F, 1F, 3F, 3F, new CubeDeformation(0.0F)),
                PartPose.offset(-1.9F, 12F, 0F));
        root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                .texOffs(112, 16).mirror().addBox(-2F, 6F, -2F, 4F, 6F, 4F, new CubeDeformation(1.0F))
                .texOffs(48, 44).mirror().addBox(-2.5F, 10F, -4.2F, 5F, 2F, 2.2F, new CubeDeformation(0.0F))
                .texOffs(76, 36).mirror().addBox(-2F, 4.5F, -3.7F, 4F, 5F, 1F, new CubeDeformation(0.0F))
                .texOffs(86, 36).mirror().addBox(2.4F, 7F, -1F, 1F, 3F, 3F, new CubeDeformation(0.0F)),
                PartPose.offset(1.9F, 12F, 0F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    public static LayerDefinition inner() {
        MeshDefinition mesh = HumanoidModel.createMesh(CubeDeformation.NONE, 0.0F);
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("head", CubeListBuilder.create(),
                PartPose.offset(0F, 0F, 0F));
        root.addOrReplaceChild("hat", CubeListBuilder.create(),
                PartPose.offset(0F, 0F, 0F));
        root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(44, 0).mirror(false).addBox(-4F, 9F, -2F, 8F, 3F, 4F, new CubeDeformation(0.6F))
                .texOffs(108, 0).mirror(false).addBox(-1.5F, 9.3F, -3.0F, 3F, 2.4F, 1F, new CubeDeformation(0.0F))
                .texOffs(32, 0).mirror(false).addBox(-2.5F, 11.5F, -2.9F, 5F, 7F, 1F, new CubeDeformation(0.0F))
                .texOffs(68, 0).mirror(false).addBox(-4.2F, 11.5F, -2.8F, 1.6F, 4F, 1F, new CubeDeformation(0.0F))
                .texOffs(74, 0).mirror().addBox(2.6F, 11.5F, -2.8F, 1.6F, 4F, 1F, new CubeDeformation(0.0F)),
                PartPose.offset(0F, 0F, 0F));
        root.addOrReplaceChild("right_arm", CubeListBuilder.create(),
                PartPose.offset(-5F, 2F, 0F));
        root.addOrReplaceChild("left_arm", CubeListBuilder.create(),
                PartPose.offset(5F, 2F, 0F));
        root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                .texOffs(0, 0).mirror(false).addBox(-2F, 0F, -2F, 4F, 8F, 4F, new CubeDeformation(0.55F))
                .texOffs(80, 0).mirror(false).addBox(-2.5F, 5F, -3.4F, 5F, 3F, 1.5F, new CubeDeformation(0.0F)),
                PartPose.offset(-1.9F, 12F, 0F));
        root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                .texOffs(16, 0).mirror().addBox(-2F, 0F, -2F, 4F, 8F, 4F, new CubeDeformation(0.55F))
                .texOffs(94, 0).mirror().addBox(-2.5F, 5F, -3.4F, 5F, 3F, 1.5F, new CubeDeformation(0.0F)),
                PartPose.offset(1.9F, 12F, 0F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    private CelestialArmorLayers() {
    }
}
