package com.steelstorm.arsenal.client;

import net.minecraft.client.model.HumanoidModel;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Cube layout of the 3D voidwalker armour. Generated by tools/gen_armor3d.py together with its
 * textures; edit the script, not this file.
 */
public final class VoidwalkerArmorLayers {
    public static LayerDefinition outer() {
        MeshDefinition mesh = HumanoidModel.createMesh(CubeDeformation.NONE, 0.0F);
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("head", CubeListBuilder.create()
                .texOffs(0, 0).mirror(false).addBox(-4F, -8F, -4F, 8F, 8F, 8F, new CubeDeformation(1.0F))
                .texOffs(0, 16).mirror(false).addBox(-4.6F, -8.8F, -4.2F, 9.2F, 3F, 9F, new CubeDeformation(0.0F))
                .texOffs(50, 37).mirror(false).addBox(-3F, -5F, -5.3F, 6F, 1F, 1F, new CubeDeformation(0.0F))
                .texOffs(88, 28).mirror(false).addBox(-0.75F, -12.5F, -1.5F, 1.5F, 4F, 1.5F, new CubeDeformation(0.0F))
                .texOffs(0, 37).mirror(false).addBox(-3.5F, -11F, -0.5F, 1F, 3F, 1F, new CubeDeformation(0.0F))
                .texOffs(4, 37).mirror().addBox(2.5F, -11F, -0.5F, 1F, 3F, 1F, new CubeDeformation(0.0F)),
                PartPose.offset(0F, 0F, 0F));
        root.addOrReplaceChild("hat", CubeListBuilder.create(),
                PartPose.offset(0F, 0F, 0F));
        root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(32, 0).mirror(false).addBox(-4F, 0F, -2F, 8F, 12F, 4F, new CubeDeformation(1.01F))
                .texOffs(38, 16).mirror(false).addBox(-4.3F, 0.5F, -3.7F, 8.6F, 9F, 1F, new CubeDeformation(0.0F))
                .texOffs(8, 37).mirror(false).addBox(-1F, 2.5F, -4.5F, 2F, 3F, 1F, new CubeDeformation(0.0F))
                .texOffs(88, 0).mirror(false).addBox(-4F, 0F, 2.8F, 8F, 13F, 1F, new CubeDeformation(0.0F))
                .texOffs(96, 28).mirror(false).addBox(-3.5F, -1.5F, 2.2F, 1.2F, 3F, 1.2F, new CubeDeformation(0.0F))
                .texOffs(104, 28).mirror().addBox(2.3F, -1.5F, 2.2F, 1.2F, 3F, 1.2F, new CubeDeformation(0.0F)),
                PartPose.offset(0F, 0F, 0F));
        root.addOrReplaceChild("right_arm", CubeListBuilder.create()
                .texOffs(56, 0).mirror(false).addBox(-3F, -2F, -2F, 4F, 12F, 4F, new CubeDeformation(1.0F))
                .texOffs(90, 16).mirror(false).addBox(-4.6F, -3.5F, -3F, 5.5F, 3F, 6F, new CubeDeformation(0.0F))
                .texOffs(112, 28).mirror(false).addBox(-4.5F, -6F, -1F, 1.5F, 3F, 1.5F, new CubeDeformation(0.0F))
                .texOffs(42, 37).mirror(false).addBox(-2.8F, -5.2F, 0.6F, 1F, 2F, 1F, new CubeDeformation(0.0F))
                .texOffs(24, 28).mirror(false).addBox(-3.5F, 6F, -2.5F, 5F, 3F, 5F, new CubeDeformation(0.25F))
                .texOffs(64, 37).mirror(false).addBox(-3.6F, 7F, -2.8F, 5F, 1F, 1F, new CubeDeformation(0.0F)),
                PartPose.offset(-5F, 2F, 0F));
        root.addOrReplaceChild("left_arm", CubeListBuilder.create()
                .texOffs(72, 0).mirror().addBox(-1F, -2F, -2F, 4F, 12F, 4F, new CubeDeformation(1.0F))
                .texOffs(0, 28).mirror().addBox(-0.9F, -3.5F, -3F, 5.5F, 3F, 6F, new CubeDeformation(0.0F))
                .texOffs(120, 28).mirror().addBox(3.0F, -6F, -1F, 1.5F, 3F, 1.5F, new CubeDeformation(0.0F))
                .texOffs(46, 37).mirror().addBox(1.8F, -5.2F, 0.6F, 1F, 2F, 1F, new CubeDeformation(0.0F))
                .texOffs(44, 28).mirror().addBox(-1.5F, 6F, -2.5F, 5F, 3F, 5F, new CubeDeformation(0.25F))
                .texOffs(76, 37).mirror().addBox(-1.4F, 7F, -2.8F, 5F, 1F, 1F, new CubeDeformation(0.0F)),
                PartPose.offset(5F, 2F, 0F));
        root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                .texOffs(58, 16).mirror(false).addBox(-2F, 6F, -2F, 4F, 6F, 4F, new CubeDeformation(1.0F))
                .texOffs(14, 37).mirror(false).addBox(-2.3F, 10F, -3.6F, 4.6F, 2F, 1.6F, new CubeDeformation(0.0F))
                .texOffs(64, 28).mirror(false).addBox(-2.4F, 7F, -2.6F, 0.6F, 3F, 5F, new CubeDeformation(0.0F)),
                PartPose.offset(-1.9F, 12F, 0F));
        root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                .texOffs(74, 16).mirror().addBox(-2F, 6F, -2F, 4F, 6F, 4F, new CubeDeformation(1.0F))
                .texOffs(28, 37).mirror().addBox(-2.3F, 10F, -3.6F, 4.6F, 2F, 1.6F, new CubeDeformation(0.0F))
                .texOffs(76, 28).mirror().addBox(1.8F, 7F, -2.6F, 0.6F, 3F, 5F, new CubeDeformation(0.0F)),
                PartPose.offset(1.9F, 12F, 0F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    public static LayerDefinition inner() {
        MeshDefinition mesh = HumanoidModel.createMesh(CubeDeformation.NONE, 0.0F);
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("head", CubeListBuilder.create(),
                PartPose.offset(0F, 0F, 0F));
        root.addOrReplaceChild("hat", CubeListBuilder.create(),
                PartPose.offset(0F, 0F, 0F));
        root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(32, 0).mirror(false).addBox(-4F, 9F, -2F, 8F, 3F, 4F, new CubeDeformation(0.6F))
                .texOffs(100, 0).mirror(false).addBox(-1F, 9.5F, -3.0F, 2F, 2F, 1F, new CubeDeformation(0.0F))
                .texOffs(56, 0).mirror(false).addBox(-3.5F, 11.5F, -2.9F, 7F, 6F, 1F, new CubeDeformation(0.0F)),
                PartPose.offset(0F, 0F, 0F));
        root.addOrReplaceChild("right_arm", CubeListBuilder.create(),
                PartPose.offset(-5F, 2F, 0F));
        root.addOrReplaceChild("left_arm", CubeListBuilder.create(),
                PartPose.offset(5F, 2F, 0F));
        root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                .texOffs(0, 0).mirror(false).addBox(-2F, 0F, -2F, 4F, 8F, 4F, new CubeDeformation(0.55F))
                .texOffs(72, 0).mirror(false).addBox(-2.3F, 5F, -3.2F, 4.6F, 2.5F, 1.2F, new CubeDeformation(0.0F)),
                PartPose.offset(-1.9F, 12F, 0F));
        root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                .texOffs(16, 0).mirror().addBox(-2F, 0F, -2F, 4F, 8F, 4F, new CubeDeformation(0.55F))
                .texOffs(86, 0).mirror().addBox(-2.3F, 5F, -3.2F, 4.6F, 2.5F, 1.2F, new CubeDeformation(0.0F)),
                PartPose.offset(1.9F, 12F, 0F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    private VoidwalkerArmorLayers() {
    }
}
