package com.steelstorm.arsenal.datagen;

import com.steelstorm.arsenal.SteelstormArsenal;
import com.steelstorm.arsenal.registry.ModItems;
import com.steelstorm.arsenal.weapon.Rune;
import com.steelstorm.arsenal.weapon.LegendaryWeaponItem;
import com.steelstorm.arsenal.weapon.WeaponItem;
import java.util.List;
import java.util.Map;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.data.PackOutput;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemDisplayContext;
import net.neoforged.neoforge.client.model.generators.ItemModelBuilder;
import net.neoforged.neoforge.client.model.generators.ItemModelProvider;
import net.neoforged.neoforge.client.model.generators.loaders.SeparateTransformsModelBuilder;
import net.neoforged.neoforge.common.data.ExistingFileHelper;
import net.neoforged.neoforge.registries.DeferredItem;

/**
 * Weapons use NeoForge's separate-transforms loader: the flat 32x32 icon in inventories, item
 * frames and on the ground, and a full 3D model (models/item/3d, generated by tools/gen_models.py)
 * when held or displayed on a weapon rack.
 */
public class ModItemModelProvider extends ItemModelProvider {
    public ModItemModelProvider(PackOutput output, ExistingFileHelper files) {
        super(output, SteelstormArsenal.MODID, files);
    }

    @Override
    protected void registerModels() {
        for (DeferredItem<WeaponItem> weapon : ModItems.tieredWeapons()) {
            WeaponItem item = weapon.get();
            // Every tier has its own 3D model (tools/gen_tier_models.py) with its textures built in.
            weapon3d(item, BuiltInRegistries.ITEM.getKey(item).getPath(), Map.of());
        }
        for (LegendaryWeaponItem.Legendary legendary : LegendaryWeaponItem.Legendary.values()) {
            weapon3d(ModItems.legendary(legendary).get(), legendary.id(), Map.of());
        }
        weapon3d(ModItems.CHAKRAM.get(), "chakram", Map.of());
        weapon3d(ModItems.THROWING_KNIFE.get(), "throwing_knife", Map.of());

        basicItem(ModItems.STORMSTEEL_INGOT.get());
        basicItem(ModItems.RAW_STORMSTEEL.get());
        basicItem(ModItems.TARGET_DUMMY.get());
        for (Rune rune : Rune.values()) {
            basicItem(ModItems.rune(rune).get());
        }
        basicItem(ModItems.VAULT_KEY.get());
        basicItem(ModItems.EXPLORERS_COMPASS.get());
        basicItem(ModItems.STORMSTEEL_HELMET.get());
        basicItem(ModItems.STORMSTEEL_CHESTPLATE.get());
        basicItem(ModItems.STORMSTEEL_LEGGINGS.get());
        basicItem(ModItems.STORMSTEEL_BOOTS.get());
        basicItem(ModItems.WARLORD_HELMET.get());
        basicItem(ModItems.WARLORD_CHESTPLATE.get());
        basicItem(ModItems.WARLORD_LEGGINGS.get());
        basicItem(ModItems.WARLORD_BOOTS.get());
        for (var egg : List.of(ModItems.BANDIT_DUELIST_SPAWN_EGG, ModItems.BANDIT_ARCHER_SPAWN_EGG,
                ModItems.IRON_REVENANT_SPAWN_EGG, ModItems.FALLEN_WARLORD_SPAWN_EGG, ModItems.BANDIT_CAPTAIN_SPAWN_EGG,
                ModItems.CRYPT_KNIGHT_SPAWN_EGG, ModItems.STORM_HERALD_SPAWN_EGG, ModItems.FORGE_COLOSSUS_SPAWN_EGG,
                ModItems.MOONBLADE_REVENANT_SPAWN_EGG)) {
            withExistingParent(egg.getId().getPath(), mcLoc("item/template_spawn_egg"));
        }
    }

    private void weapon3d(Item item, String model3d, Map<String, String> textures) {
        String name = BuiltInRegistries.ITEM.getKey(item).getPath();
        ItemModelBuilder base = nested().parent(getExistingFile(modLoc("item/3d/" + model3d)));
        textures.forEach((key, value) -> base.texture(key, modLoc(value)));
        getBuilder(name).customLoader(SeparateTransformsModelBuilder::begin)
                .base(base)
                .perspective(ItemDisplayContext.GUI, icon(name))
                .perspective(ItemDisplayContext.GROUND, icon(name))
                .perspective(ItemDisplayContext.FIXED, icon(name))
                .end();
    }

    private ItemModelBuilder icon(String name) {
        return nested().parent(getExistingFile(mcLoc("item/generated"))).texture("layer0", modLoc("item/" + name));
    }

}
