package com.steelstorm.arsenal.client;

import net.minecraft.client.model.HumanoidModel;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Cube layout of the 3D stormsteel armour. Generated by tools/gen_armor3d.py together with its
 * textures; edit the script, not this file.
 */
public final class StormsteelArmorLayers {
    public static LayerDefinition outer() {
        MeshDefinition mesh = HumanoidModel.createMesh(CubeDeformation.NONE, 0.0F);
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("head", CubeListBuilder.create()
                .texOffs(0, 0).mirror(false).addBox(-4F, -8F, -4F, 8F, 8F, 8F, new CubeDeformation(1.0F))
                .texOffs(88, 0).mirror(false).addBox(-0.5F, -12.5F, -5F, 1F, 4F, 10F, new CubeDeformation(0.0F))
                .texOffs(52, 36).mirror(false).addBox(-4.5F, -6.5F, -5.7F, 9F, 2F, 1F, new CubeDeformation(0.0F))
                .texOffs(84, 16).mirror(false).addBox(-5.6F, -4.5F, -3.5F, 1F, 4F, 5F, new CubeDeformation(0.0F))
                .texOffs(96, 16).mirror().addBox(4.6F, -4.5F, -3.5F, 1F, 4F, 5F, new CubeDeformation(0.0F))
                .texOffs(108, 16).mirror(false).addBox(-6.8F, -10F, -1F, 1F, 5F, 4F, new CubeDeformation(0.0F))
                .texOffs(118, 16).mirror().addBox(5.8F, -10F, -1F, 1F, 5F, 4F, new CubeDeformation(0.0F)),
                PartPose.offset(0F, 0F, 0F));
        root.addOrReplaceChild("hat", CubeListBuilder.create(),
                PartPose.offset(0F, 0F, 0F));
        root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(32, 0).mirror(false).addBox(-4F, 0F, -2F, 8F, 12F, 4F, new CubeDeformation(1.01F))
                .texOffs(84, 27).mirror(false).addBox(-3.5F, 1F, -3.8F, 7F, 6F, 1F, new CubeDeformation(0.0F))
                .texOffs(72, 36).mirror(false).addBox(-1F, 3F, -4.6F, 2F, 2F, 1F, new CubeDeformation(0.0F))
                .texOffs(0, 27).mirror(false).addBox(-3F, 1F, 2.8F, 6F, 8F, 1F, new CubeDeformation(0.0F))
                .texOffs(14, 27).mirror(false).addBox(-4.5F, -1F, -3F, 9F, 2F, 6F, new CubeDeformation(0.0F)),
                PartPose.offset(0F, 0F, 0F));
        root.addOrReplaceChild("right_arm", CubeListBuilder.create()
                .texOffs(56, 0).mirror(false).addBox(-3F, -2F, -2F, 4F, 12F, 4F, new CubeDeformation(1.0F))
                .texOffs(0, 16).mirror(false).addBox(-5F, -4F, -3.5F, 6F, 4F, 7F, new CubeDeformation(0.0F))
                .texOffs(0, 36).mirror(false).addBox(-4F, -5.5F, -1F, 4F, 2F, 2F, new CubeDeformation(0.0F))
                .texOffs(44, 27).mirror(false).addBox(-3.5F, 6F, -2.5F, 5F, 3F, 5F, new CubeDeformation(0.25F)),
                PartPose.offset(-5F, 2F, 0F));
        root.addOrReplaceChild("left_arm", CubeListBuilder.create()
                .texOffs(72, 0).mirror().addBox(-1F, -2F, -2F, 4F, 12F, 4F, new CubeDeformation(1.0F))
                .texOffs(26, 16).mirror().addBox(-1F, -4F, -3.5F, 6F, 4F, 7F, new CubeDeformation(0.0F))
                .texOffs(12, 36).mirror().addBox(0F, -5.5F, -1F, 4F, 2F, 2F, new CubeDeformation(0.0F))
                .texOffs(64, 27).mirror().addBox(-1.5F, 6F, -2.5F, 5F, 3F, 5F, new CubeDeformation(0.25F)),
                PartPose.offset(5F, 2F, 0F));
        root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                .texOffs(52, 16).mirror(false).addBox(-2F, 6F, -2F, 4F, 6F, 4F, new CubeDeformation(1.0F))
                .texOffs(24, 36).mirror(false).addBox(-2.5F, 10F, -4F, 5F, 2F, 2F, new CubeDeformation(0.0F))
                .texOffs(100, 27).mirror(false).addBox(-2F, 5F, -3.6F, 4F, 4F, 1F, new CubeDeformation(0.0F)),
                PartPose.offset(-1.9F, 12F, 0F));
        root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                .texOffs(68, 16).mirror().addBox(-2F, 6F, -2F, 4F, 6F, 4F, new CubeDeformation(1.0F))
                .texOffs(38, 36).mirror().addBox(-2.5F, 10F, -4F, 5F, 2F, 2F, new CubeDeformation(0.0F))
                .texOffs(110, 27).mirror().addBox(-2F, 5F, -3.6F, 4F, 4F, 1F, new CubeDeformation(0.0F)),
                PartPose.offset(1.9F, 12F, 0F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    public static LayerDefinition inner() {
        MeshDefinition mesh = HumanoidModel.createMesh(CubeDeformation.NONE, 0.0F);
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("head", CubeListBuilder.create(),
                PartPose.offset(0F, 0F, 0F));
        root.addOrReplaceChild("hat", CubeListBuilder.create(),
                PartPose.offset(0F, 0F, 0F));
        root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(32, 0).mirror(false).addBox(-4F, 9F, -2F, 8F, 3F, 4F, new CubeDeformation(0.6F))
                .texOffs(56, 0).mirror(false).addBox(-4F, 11.5F, -3.0F, 3.5F, 4F, 1F, new CubeDeformation(0.0F))
                .texOffs(66, 0).mirror().addBox(0.5F, 11.5F, -3.0F, 3.5F, 4F, 1F, new CubeDeformation(0.0F))
                .texOffs(104, 0).mirror(false).addBox(-1F, 9.5F, -3.0F, 2F, 2F, 1F, new CubeDeformation(0.0F)),
                PartPose.offset(0F, 0F, 0F));
        root.addOrReplaceChild("right_arm", CubeListBuilder.create(),
                PartPose.offset(-5F, 2F, 0F));
        root.addOrReplaceChild("left_arm", CubeListBuilder.create(),
                PartPose.offset(5F, 2F, 0F));
        root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                .texOffs(0, 0).mirror(false).addBox(-2F, 0F, -2F, 4F, 8F, 4F, new CubeDeformation(0.55F))
                .texOffs(76, 0).mirror(false).addBox(-2.5F, 5F, -3.3F, 5F, 3F, 1.5F, new CubeDeformation(0.0F)),
                PartPose.offset(-1.9F, 12F, 0F));
        root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                .texOffs(16, 0).mirror().addBox(-2F, 0F, -2F, 4F, 8F, 4F, new CubeDeformation(0.55F))
                .texOffs(90, 0).mirror().addBox(-2.5F, 5F, -3.3F, 5F, 3F, 1.5F, new CubeDeformation(0.0F)),
                PartPose.offset(1.9F, 12F, 0F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    private StormsteelArmorLayers() {
    }
}
