package com.steelstorm.arsenal.client;

import net.minecraft.client.model.HumanoidModel;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/**
 * Cube layout of the 3D warlord armour. Generated by tools/gen_armor3d.py together with its
 * textures; edit the script, not this file.
 */
public final class WarlordArmorLayers {
    public static LayerDefinition outer() {
        MeshDefinition mesh = HumanoidModel.createMesh(CubeDeformation.NONE, 0.0F);
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("head", CubeListBuilder.create()
                .texOffs(0, 0).mirror(false).addBox(-4F, -8F, -4F, 8F, 8F, 8F, new CubeDeformation(1.0F))
                .texOffs(64, 36).mirror(false).addBox(-4.5F, -5.5F, -5.6F, 9F, 3F, 1F, new CubeDeformation(0.0F))
                .texOffs(16, 41).mirror(false).addBox(-3F, -4.8F, -5.9F, 6F, 1F, 1F, new CubeDeformation(0.0F))
                .texOffs(94, 0).mirror(false).addBox(-1F, -10F, -4.5F, 2F, 2F, 9F, new CubeDeformation(0.0F))
                .texOffs(20, 27).mirror(false).addBox(-7.5F, -11F, -1F, 2F, 6F, 2F, new CubeDeformation(0.0F))
                .texOffs(84, 36).mirror(false).addBox(-8.5F, -14F, -0.5F, 1F, 3F, 1F, new CubeDeformation(0.0F))
                .texOffs(28, 27).mirror().addBox(5.5F, -11F, -1F, 2F, 6F, 2F, new CubeDeformation(0.0F))
                .texOffs(88, 36).mirror().addBox(7.5F, -14F, -0.5F, 1F, 3F, 1F, new CubeDeformation(0.0F))
                .texOffs(0, 36).mirror(false).addBox(-4.5F, -2F, -5F, 9F, 2F, 3F, new CubeDeformation(0.0F)),
                PartPose.offset(0F, 0F, 0F));
        root.addOrReplaceChild("hat", CubeListBuilder.create(),
                PartPose.offset(0F, 0F, 0F));
        root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(32, 0).mirror(false).addBox(-4F, 0F, -2F, 8F, 12F, 4F, new CubeDeformation(1.01F))
                .texOffs(36, 27).mirror(false).addBox(-4.5F, 0.5F, -3.9F, 9F, 7F, 1F, new CubeDeformation(0.0F))
                .texOffs(92, 36).mirror(false).addBox(-1.5F, 2.5F, -4.7F, 3F, 3F, 1F, new CubeDeformation(0.0F))
                .texOffs(100, 36).mirror(false).addBox(-3.5F, 7.5F, -3.6F, 7F, 3F, 1F, new CubeDeformation(0.0F))
                .texOffs(56, 16).mirror(false).addBox(-3.5F, 0.5F, 2.8F, 7F, 9F, 1F, new CubeDeformation(0.0F))
                .texOffs(88, 0).mirror(false).addBox(-0.5F, -1F, 3.6F, 1F, 10F, 2F, new CubeDeformation(0.0F))
                .texOffs(56, 27).mirror(false).addBox(-4.5F, -1.5F, -3F, 9F, 2F, 6F, new CubeDeformation(0.0F)),
                PartPose.offset(0F, 0F, 0F));
        root.addOrReplaceChild("right_arm", CubeListBuilder.create()
                .texOffs(56, 0).mirror(false).addBox(-3F, -2F, -2F, 4F, 12F, 4F, new CubeDeformation(1.0F))
                .texOffs(0, 16).mirror(false).addBox(-5.5F, -4.5F, -3.5F, 7F, 4F, 7F, new CubeDeformation(0.0F))
                .texOffs(116, 36).mirror(false).addBox(-5F, -7.5F, -0.5F, 1F, 3F, 1F, new CubeDeformation(0.0F))
                .texOffs(24, 36).mirror(false).addBox(-3F, -8F, -0.5F, 1F, 3.5F, 1F, new CubeDeformation(0.0F))
                .texOffs(120, 36).mirror(false).addBox(-1F, -7F, -0.5F, 1F, 2.5F, 1F, new CubeDeformation(0.0F))
                .texOffs(104, 16).mirror(false).addBox(-3.6F, 6F, -2.6F, 5F, 4F, 5F, new CubeDeformation(0.25F))
                .texOffs(30, 41).mirror(false).addBox(-3.6F, 9.5F, -2.8F, 5F, 1F, 1F, new CubeDeformation(0.0F)),
                PartPose.offset(-5F, 2F, 0F));
        root.addOrReplaceChild("left_arm", CubeListBuilder.create()
                .texOffs(72, 0).mirror().addBox(-1F, -2F, -2F, 4F, 12F, 4F, new CubeDeformation(1.0F))
                .texOffs(28, 16).mirror().addBox(-1.5F, -4.5F, -3.5F, 7F, 4F, 7F, new CubeDeformation(0.0F))
                .texOffs(124, 36).mirror().addBox(4F, -7.5F, -0.5F, 1F, 3F, 1F, new CubeDeformation(0.0F))
                .texOffs(28, 36).mirror().addBox(2F, -8F, -0.5F, 1F, 3.5F, 1F, new CubeDeformation(0.0F))
                .texOffs(0, 41).mirror().addBox(0F, -7F, -0.5F, 1F, 2.5F, 1F, new CubeDeformation(0.0F))
                .texOffs(0, 27).mirror().addBox(-1.4F, 6F, -2.6F, 5F, 4F, 5F, new CubeDeformation(0.25F))
                .texOffs(42, 41).mirror().addBox(-1.4F, 9.5F, -2.8F, 5F, 1F, 1F, new CubeDeformation(0.0F)),
                PartPose.offset(5F, 2F, 0F));
        root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                .texOffs(72, 16).mirror(false).addBox(-2F, 6F, -2F, 4F, 6F, 4F, new CubeDeformation(1.0F))
                .texOffs(32, 36).mirror(false).addBox(-2.5F, 10F, -4.2F, 5F, 2F, 2.2F, new CubeDeformation(0.0F))
                .texOffs(86, 27).mirror(false).addBox(-2F, 4.5F, -3.7F, 4F, 5F, 1F, new CubeDeformation(0.0F))
                .texOffs(4, 41).mirror(false).addBox(-0.5F, 9F, 2.5F, 1F, 1F, 2F, new CubeDeformation(0.0F)),
                PartPose.offset(-1.9F, 12F, 0F));
        root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                .texOffs(88, 16).mirror().addBox(-2F, 6F, -2F, 4F, 6F, 4F, new CubeDeformation(1.0F))
                .texOffs(48, 36).mirror().addBox(-2.5F, 10F, -4.2F, 5F, 2F, 2.2F, new CubeDeformation(0.0F))
                .texOffs(96, 27).mirror().addBox(-2F, 4.5F, -3.7F, 4F, 5F, 1F, new CubeDeformation(0.0F))
                .texOffs(10, 41).mirror().addBox(-0.5F, 9F, 2.5F, 1F, 1F, 2F, new CubeDeformation(0.0F)),
                PartPose.offset(1.9F, 12F, 0F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    public static LayerDefinition inner() {
        MeshDefinition mesh = HumanoidModel.createMesh(CubeDeformation.NONE, 0.0F);
        PartDefinition root = mesh.getRoot();
        root.addOrReplaceChild("head", CubeListBuilder.create(),
                PartPose.offset(0F, 0F, 0F));
        root.addOrReplaceChild("hat", CubeListBuilder.create(),
                PartPose.offset(0F, 0F, 0F));
        root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(32, 0).mirror(false).addBox(-4F, 9F, -2F, 8F, 3F, 4F, new CubeDeformation(0.6F))
                .texOffs(120, 0).mirror(false).addBox(-1.5F, 9.3F, -3.0F, 3F, 2.4F, 1F, new CubeDeformation(0.0F))
                .texOffs(56, 0).mirror(false).addBox(-4.2F, 11.5F, -3.0F, 3.6F, 5F, 1F, new CubeDeformation(0.0F))
                .texOffs(66, 0).mirror().addBox(0.6F, 11.5F, -3.0F, 3.6F, 5F, 1F, new CubeDeformation(0.0F))
                .texOffs(76, 0).mirror(false).addBox(-3.5F, 11.5F, 2.0F, 7F, 4F, 1F, new CubeDeformation(0.0F)),
                PartPose.offset(0F, 0F, 0F));
        root.addOrReplaceChild("right_arm", CubeListBuilder.create(),
                PartPose.offset(-5F, 2F, 0F));
        root.addOrReplaceChild("left_arm", CubeListBuilder.create(),
                PartPose.offset(5F, 2F, 0F));
        root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                .texOffs(0, 0).mirror(false).addBox(-2F, 0F, -2F, 4F, 8F, 4F, new CubeDeformation(0.55F))
                .texOffs(92, 0).mirror(false).addBox(-2.5F, 5F, -3.4F, 5F, 3F, 1.5F, new CubeDeformation(0.0F))
                .texOffs(0, 12).mirror(false).addBox(-0.5F, 5.5F, -4.6F, 1F, 1F, 1.4F, new CubeDeformation(0.0F)),
                PartPose.offset(-1.9F, 12F, 0F));
        root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                .texOffs(16, 0).mirror().addBox(-2F, 0F, -2F, 4F, 8F, 4F, new CubeDeformation(0.55F))
                .texOffs(106, 0).mirror().addBox(-2.5F, 5F, -3.4F, 5F, 3F, 1.5F, new CubeDeformation(0.0F))
                .texOffs(6, 12).mirror().addBox(-0.5F, 5.5F, -4.6F, 1F, 1F, 1.4F, new CubeDeformation(0.0F)),
                PartPose.offset(1.9F, 12F, 0F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    private WarlordArmorLayers() {
    }
}
