package com.steelstorm.arsenal.client.boss;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Boss model layouts, generated by tools/gen_bosses.py together with their textures. */
public final class BossLayers {
    public static LayerDefinition forgeColossus() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot().addOrReplaceChild("root", CubeListBuilder.create(), PartPose.offset(0F, 24F, 0F));
        PartDefinition hips = root.addOrReplaceChild("hips", CubeListBuilder.create()
                .texOffs(36, 58).mirror(false).addBox(-7F, -4F, -5F, 14F, 6F, 10F),
                PartPose.offset(0F, -18F, 0F));
        PartDefinition torso = hips.addOrReplaceChild("torso", CubeListBuilder.create()
                .texOffs(0, 0).mirror(false).addBox(-12F, -20F, -8F, 24F, 20F, 16F)
                .texOffs(32, 88).mirror(false).addBox(-10F, -18F, -9F, 20F, 4F, 1F)
                .texOffs(136, 76).mirror(false).addBox(-4F, -14F, -10F, 8F, 8F, 2F)
                .texOffs(124, 88).mirror(false).addBox(-6F, -16F, -9.5F, 12F, 1F, 1F)
                .texOffs(0, 76).mirror(false).addBox(-11F, -22F, 4F, 22F, 6F, 6F)
                .texOffs(120, 76).mirror(false).addBox(-3F, -30F, 4F, 2F, 9F, 2F)
                .texOffs(128, 76).mirror(false).addBox(1F, -30F, 4F, 2F, 9F, 2F),
                PartPose.offset(0F, -2F, 0F));
        PartDefinition head = torso.addOrReplaceChild("head", CubeListBuilder.create()
                .texOffs(100, 36).mirror(false).addBox(-5F, -8F, -5F, 10F, 8F, 10F)
                .texOffs(94, 88).mirror(false).addBox(-4F, -4.5F, -5.6F, 8F, 1.5F, 1F)
                .texOffs(208, 76).mirror(false).addBox(-6F, -10F, -3F, 3F, 4F, 3F)
                .texOffs(220, 76).mirror().addBox(3F, -10F, -3F, 3F, 4F, 3F)
                .texOffs(0, 88).mirror(false).addBox(-5.5F, -1F, -5.5F, 11F, 2F, 5F),
                PartPose.offset(0F, -20F, -3F));
        PartDefinition right_arm = torso.addOrReplaceChild("right_arm", CubeListBuilder.create()
                .texOffs(80, 0).mirror(false).addBox(-7F, -4F, -7F, 9F, 9F, 14F)
                .texOffs(156, 76).mirror(false).addBox(-6F, -6F, -3F, 7F, 2F, 6F)
                .texOffs(44, 36).mirror(false).addBox(-5.5F, 5F, -4F, 6F, 13F, 8F),
                PartPose.offset(-14F, -16F, 0F));
        PartDefinition right_forearm = right_arm.addOrReplaceChild("right_forearm", CubeListBuilder.create()
                .texOffs(140, 36).mirror(false).addBox(-3.5F, 0F, -4.5F, 7F, 9F, 9F)
                .texOffs(84, 58).mirror(false).addBox(-4.5F, 7F, -6F, 9F, 2F, 12F)
                .texOffs(172, 0).mirror(false).addBox(-5.0F, 9F, -6F, 10F, 10F, 12F)
                .texOffs(74, 88).mirror(false).addBox(-2.0F, 13F, -6.6F, 4F, 3F, 1F),
                PartPose.offset(-2.5F, 18F, 0F));
        PartDefinition right_leg = root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                .texOffs(172, 36).mirror(false).addBox(-4.5F, 0F, -4.5F, 9F, 9F, 9F)
                .texOffs(56, 76).mirror(false).addBox(-4F, 9F, -4F, 8F, 4F, 8F)
                .texOffs(126, 58).mirror(false).addBox(-5F, 13F, -7F, 10F, 3F, 11F)
                .texOffs(112, 88).mirror(false).addBox(-1F, 4F, -5F, 2F, 2F, 1F),
                PartPose.offset(-6F, -16F, 0F));
        PartDefinition left_arm = torso.addOrReplaceChild("left_arm", CubeListBuilder.create()
                .texOffs(126, 0).mirror().addBox(-2F, -4F, -7F, 9F, 9F, 14F)
                .texOffs(182, 76).mirror().addBox(-1F, -6F, -3F, 7F, 2F, 6F)
                .texOffs(72, 36).mirror().addBox(-0.5F, 5F, -4F, 6F, 13F, 8F),
                PartPose.offset(14F, -16F, 0F));
        PartDefinition left_forearm = left_arm.addOrReplaceChild("left_forearm", CubeListBuilder.create()
                .texOffs(208, 36).mirror().addBox(-3.5F, 0F, -4.5F, 7F, 9F, 9F)
                .texOffs(168, 58).mirror().addBox(-4.5F, 7F, -6F, 9F, 2F, 12F)
                .texOffs(0, 36).mirror().addBox(-5.0F, 9F, -6F, 10F, 10F, 12F)
                .texOffs(84, 88).mirror().addBox(-2.0F, 13F, -6.6F, 4F, 3F, 1F),
                PartPose.offset(2.5F, 18F, 0F));
        PartDefinition left_leg = root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                .texOffs(0, 58).mirror().addBox(-4.5F, 0F, -4.5F, 9F, 9F, 9F)
                .texOffs(88, 76).mirror().addBox(-4F, 9F, -4F, 8F, 4F, 8F)
                .texOffs(210, 58).mirror().addBox(-5F, 13F, -7F, 10F, 3F, 11F)
                .texOffs(118, 88).mirror().addBox(-1F, 4F, -5F, 2F, 2F, 1F),
                PartPose.offset(6F, -16F, 0F));
        return LayerDefinition.create(mesh, 256, 128);
    }

    public static LayerDefinition moonbladeRevenant() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot().addOrReplaceChild("root", CubeListBuilder.create(), PartPose.offset(0F, 24F, 0F));
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(0, 0).mirror(false).addBox(-4F, -12F, -2.5F, 8F, 12F, 5F)
                .texOffs(38, 29).mirror(false).addBox(-4.5F, -12F, -3F, 9F, 3F, 6F)
                .texOffs(102, 29).mirror(false).addBox(-1F, -6F, -3.1F, 2F, 5F, 1F),
                PartPose.offset(0F, -30F, 0F));
        PartDefinition skirt = body.addOrReplaceChild("skirt", CubeListBuilder.create()
                .texOffs(26, 0).mirror(false).addBox(-5F, 0F, -3.5F, 10F, 7F, 7F)
                .texOffs(0, 29).mirror(false).addBox(-5.5F, 6F, -4F, 11F, 2F, 8F),
                PartPose.offset(0F, 0F, 0F));
        PartDefinition tail = skirt.addOrReplaceChild("tail", CubeListBuilder.create()
                .texOffs(0, 17).mirror(false).addBox(-4F, 0F, -3F, 8F, 6F, 6F)
                .texOffs(68, 29).mirror(false).addBox(-3F, 6F, -2F, 6F, 5F, 4F)
                .texOffs(88, 29).mirror(false).addBox(-2F, 11F, -1.5F, 4F, 4F, 3F),
                PartPose.offset(0F, 8F, 0F));
        PartDefinition head = body.addOrReplaceChild("head", CubeListBuilder.create()
                .texOffs(60, 0).mirror(false).addBox(-3.5F, -7F, -3.5F, 7F, 7F, 7F)
                .texOffs(12, 45).mirror(false).addBox(-3.5F, -3.5F, -3.6F, 7F, 1F, 1F)
                .texOffs(76, 17).mirror(false).addBox(-4F, -8F, -4F, 8F, 3F, 8F)
                .texOffs(108, 17).mirror(false).addBox(-4F, -7F, 2.5F, 8F, 9F, 2F)
                .texOffs(48, 39).mirror(false).addBox(-4.5F, -11F, -1F, 9F, 3F, 1F)
                .texOffs(116, 39).mirror(false).addBox(-1F, -13F, -1F, 2F, 2F, 1F),
                PartPose.offset(0F, -12F, 0F));
        PartDefinition upper_right_arm = body.addOrReplaceChild("upper_right_arm", CubeListBuilder.create()
                .texOffs(28, 17).mirror(false).addBox(-1.5F, -1F, -1.5F, 3F, 9F, 3F)
                .texOffs(108, 29).mirror(false).addBox(-1.8F, 5F, -1.8F, 3.6F, 2F, 3.6F),
                PartPose.offset(-4.5F, -11F, 0F));
        PartDefinition upper_right_blade = upper_right_arm.addOrReplaceChild("upper_right_blade", CubeListBuilder.create()
                .texOffs(68, 39).mirror(false).addBox(-1.5F, 0F, -1.5F, 3F, 1F, 3F)
                .texOffs(88, 0).mirror(false).addBox(-0.5F, 1F, -1F, 1F, 12F, 2F)
                .texOffs(112, 0).mirror(false).addBox(-0.5F, 1F, -1.4F, 1F, 12F, 0.4F)
                .texOffs(122, 39).mirror(false).addBox(-0.5F, 13F, -0.5F, 1F, 2F, 1F),
                PartPose.offset(0.0F, 8F, 0F));
        PartDefinition upper_left_arm = body.addOrReplaceChild("upper_left_arm", CubeListBuilder.create()
                .texOffs(40, 17).mirror().addBox(-1.5F, -1F, -1.5F, 3F, 9F, 3F)
                .texOffs(0, 39).mirror().addBox(-1.8F, 5F, -1.8F, 3.6F, 2F, 3.6F),
                PartPose.offset(4.5F, -11F, 0F));
        PartDefinition upper_left_blade = upper_left_arm.addOrReplaceChild("upper_left_blade", CubeListBuilder.create()
                .texOffs(80, 39).mirror().addBox(-1.5F, 0F, -1.5F, 3F, 1F, 3F)
                .texOffs(94, 0).mirror().addBox(-0.5F, 1F, -1F, 1F, 12F, 2F)
                .texOffs(116, 0).mirror().addBox(-0.5F, 1F, -1.4F, 1F, 12F, 0.4F)
                .texOffs(0, 45).mirror().addBox(-0.5F, 13F, -0.5F, 1F, 2F, 1F),
                PartPose.offset(0.0F, 8F, 0F));
        PartDefinition lower_right_arm = body.addOrReplaceChild("lower_right_arm", CubeListBuilder.create()
                .texOffs(52, 17).mirror(false).addBox(-1.5F, -1F, -1.5F, 3F, 9F, 3F)
                .texOffs(16, 39).mirror(false).addBox(-1.8F, 5F, -1.8F, 3.6F, 2F, 3.6F),
                PartPose.offset(-4.5F, -6F, 0F));
        PartDefinition lower_right_blade = lower_right_arm.addOrReplaceChild("lower_right_blade", CubeListBuilder.create()
                .texOffs(92, 39).mirror(false).addBox(-1.5F, 0F, -1.5F, 3F, 1F, 3F)
                .texOffs(100, 0).mirror(false).addBox(-0.5F, 1F, -1F, 1F, 12F, 2F)
                .texOffs(120, 0).mirror(false).addBox(-0.5F, 1F, -1.4F, 1F, 12F, 0.4F)
                .texOffs(4, 45).mirror(false).addBox(-0.5F, 13F, -0.5F, 1F, 2F, 1F),
                PartPose.offset(0.0F, 8F, 0F));
        PartDefinition lower_left_arm = body.addOrReplaceChild("lower_left_arm", CubeListBuilder.create()
                .texOffs(64, 17).mirror().addBox(-1.5F, -1F, -1.5F, 3F, 9F, 3F)
                .texOffs(32, 39).mirror().addBox(-1.8F, 5F, -1.8F, 3.6F, 2F, 3.6F),
                PartPose.offset(4.5F, -6F, 0F));
        PartDefinition lower_left_blade = lower_left_arm.addOrReplaceChild("lower_left_blade", CubeListBuilder.create()
                .texOffs(104, 39).mirror().addBox(-1.5F, 0F, -1.5F, 3F, 1F, 3F)
                .texOffs(106, 0).mirror().addBox(-0.5F, 1F, -1F, 1F, 12F, 2F)
                .texOffs(124, 0).mirror().addBox(-0.5F, 1F, -1.4F, 1F, 12F, 0.4F)
                .texOffs(8, 45).mirror().addBox(-0.5F, 13F, -0.5F, 1F, 2F, 1F),
                PartPose.offset(0.0F, 8F, 0F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    private BossLayers() {
    }
}
